windup/windup-documentation

docs/topics/Dev-Project-Information.adoc, docs/topics/templates/revision-info.adoc, docs/windup-core-development-guide/README.adoc, docs/windup-core-development-guide/master.adoc, docs/windup-rules-development-guide/master.adoc, docs/windup-user-guide/master.adoc
Also fixed build error with core development guide (though it is not being published)
=> Adding revision date to guides

docs/topics/Execute.adoc
https://issues.jboss.org/browse/WINDUP-1151
=> WINDUP-1151 adding  option into UserGuide

docs/topics/Execute.adoc
https://issues.jboss.org/browse/WINDUP-1185
=> WINDUP-1185 adding more details about offline mode

docs/topics/Execute.adoc
https://issues.jboss.org/browse/WINDUP-1195
=> WINDUP-1195 clarified help text for discoverPackages option.

docs/topics/plugin-install.adoc, docs/windup-plugin-guide/windup-eclipse-plugin-guide-early-access.html
Name has been corrected to "JBoss Tools - Windup" -- see this commit: https://github.com/windup/windup-eclipse-plugin/commit/4a7f2fabaf5a48315535e9ebf7b1593cdc07c4d2
=> update name of windup plugin update site in plugin guide

docs/topics/web-add-user.adoc, docs/topics/web-change-admin-user.adoc, docs/topics/web-enable-auth.adoc, docs/topics/web-remove-default-user.adoc, docs/windup-web-guide/windup-web-guide-early-access.html
Also condensed instructions a bit to make them a little less intimidating.
=> WINDUP-1234: Fixed issues after review

docs/windup-plugin-guide/build.cfg
For more info, see:
- https://projects.engineering.redhat.com/browse/CCS-1670
- https://mojo.redhat.com/docs/DOC-988191
=> Using workaround to fix stage build error during PDF generation

docs/topics/plugin-install.adoc, docs/topics/templates/document-attributes.adoc
Included instructions for using the Eclipse Plugin in an offline environment.
Also included attributes to ease generation of the URL in future versions.
=> WINDUP-1885: Included instructions for offline installation.

docs/topics/xml-rule-when-syntax.adoc
I've included the has-hint and has-classification when conditions in the Rules Development Guide.
=> WINDUP-1046: Included has-hint condition.

docs/topics/web-custom-rules.adoc, docs/topics/web-execution-config.adoc
Updated the descriptions for custom rulesets in the analysis configuration and Custom Rules sections of the Web Console guide.
=> WINDUP-1933: Clarified usage of including custom rules.

docs/topics/xml-rule-when-syntax.adoc
Included a rough draft of the `graph-query` when condition. This includes the `embedded-cache-libraries-01000` rule, along with the available attributes and properties.
=> WINDUP-1990: Included graph-query when condition.

docs/topics/about-cli.adoc
I've adjusted the description of the CLI tool to remove the reference to advanced users.
=> WINDUP-1942: Adjusted the text of the CLI description.

docs/maven-guide/master.adoc, docs/topics/plugin-install.adoc, docs/topics/plugin-supported-configs.adoc
Updating 4.1.x with the Eclipse Plugin Enhancements
=> Updating 4.1.x with the Eclipse Plugin Enhancements

docs/topics/maven-arguments.adoc
Corrected attribute name to use the title.
=> Corrected attribute name to use the title.

docs/topics/migration-paths.adoc
Included cloud-readiness migration paths, along with reworking the introductory paragraph and cleaning up the table's internal formatting.
=> WINDUP-2160: Included cloud-readiness in supported migration.

docs/topics/migration-paths.adoc
Janine,
I've updated this section with the Oracle JDK migration. At present, I've created a separate table for this migration path, as including it in the prior seem to fit as well. Let me know your preference, and if you have any thoughts.
=> WINDUPRULE-354: Included JDK migrations.

docs/release_notes/master.adoc, docs/topics/tattletale-release.adoc
WINDUP-2195: Incorporated feedback.
=> WINDUP-2195: Incorporated feedback.

docs/topics/known_issues.adoc, docs/topics/resolved_issues.adoc
Updated known and resolved issues.
=> Updated known and resolved issues.

docs/topics/plugin-supported-configs.adoc
WINDUP-2248: Updated Eclipse and JBDS versions.
=> WINDUP-2248: Updated Eclipse and JBDS versions.

docs/topics/about-plugin.adoc, docs/topics/method-deploy.adoc, docs/topics/plugin-install.adoc, docs/topics/plugin-intro.adoc, docs/topics/plugin-supported-configs.adoc, docs/topics/rules-testing-junit.adoc
WINDUP-2249: Renamed JBDS to RHDS
=> WINDUP-2249: Renamed JBDS to RHDS

docs/topics/plugin-install.adoc
I missed one in the prior MR, corrected the name here.
=> Corrected name.

docs/topics/templates/document-attributes.adoc
Defining Tech Preview attribute.
=> Defining Tech Preview attribute.

docs/topics/release-notes-introduction.adoc
JIRA Comment for change URL:
https://issues.redhat.com/browse/WINDUP-2478?focusedCommentId=13940397&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13940397
Changes:
* Comment out sentence about point release in Release
Notes -> Introduction.
=> WINDUP-2478: Remove sentence from Release Notes introduction

docs/topics_5/web-openshift-deploy.adoc, docs/topics_5/web-openshift-troubleshoot.adoc
Rebranding of Web Console from RHAMT to MTA
Preview: http://file.emea.redhat.com/~rhoch/06252020/Console/
=> Revised Web Console Guide

docs/topics_5/web-custom-rules.adoc
@apinnick I have removed the old screenshot and the lead-in to it.
Please take a look at Section 3.3, "Configuring an Analysis." Looks like it covers everything in Section 4, except if you think we should add information about registering a server path for files and labels. WDYT? 
Preview: http://file.emea.redhat.com/~rhoch/07092020/Section4
=> Fixing Section 4

docs/topics_5/plugin-supported-configs.adoc
Resolves Shveta Sachdeva's comment to https://issues.redhat.com/browse/WINDUP-2563.
=> IDE Plugin for MTA 5.0: Supported Configurations

docs/topics_5/web-execution-config.adoc
Small typo fix. Typo confirmed by Phil. 
@apinnick: please review.
=> "label/labels" for "rule/rules"

docs/topics_5/rn-known-issues.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2707 by adding two known issues to the of the Known issues table.
=> Additional known issues

docs/topics_5/rn-known-issues.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2757
=> Eclipse plugin null pointer exception

docs/topics_5/installation.adoc, docs/topics_5/plugin-supported-configs.adoc, docs/topics_5/rn-known-issues.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2762
=> Use Eclipse 2020-09 with MTA 5.0.1

docs/topics_5/installing-web-console-on-openshift.adoc, docs/topics_5/installing-web-console.adoc, docs/topics_5/web-openshift-access.adoc, docs/topics_5/web-openshift-troubleshoot.adoc, docs/web-console-guide_5/master.adoc
https://issues.redhat.com/browse/WINDUP-2784
Preview build: http://file.tlv.redhat.com/~apinnick/mta-operator_web-console-guide_5/#installing_the_web_console_on_red_hat_openshift_container_platform
=> mta operator installation on openshift

docs/topics_5/migration-paths.adoc
Resolves "Docs issue -- migration matrix update" in https://docs.google.com/spreadsheets/d/1av_c1ZrBS6IhClXJE3sgQnd_7eXa2rxs_0SIv4lyUqM/edit?ts=5fcdfdf3#gid=0
Preview: http://file.emea.redhat.com/rhoch/10122020/Matrix/html-single/#migration_paths_getting-started-guide
=> Add Quarkus to Supported migration paths table

docs/topics_5/rn-known-issues.adoc, docs/topics_5/rn-resolved-issues.adoc, docs/topics_5/templates/document-attributes.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2944
Preview: http://file.emea.redhat.com/rhoch/18012021/rn_511/html-single/
=> Release notes for MTA 5.1.1

docs/topics_5/rn-known-issues.adoc, docs/topics_5/rn-resolved-issues.adoc
Changes accidently left out of previous PR and additional changes requested by Phil C in https://issues.redhat.com/browse/WINDUP-2944.
Preview: http://file.emea.redhat.com/rhoch/19012021/rn2/html-single/#rn-resolved-issues_release-notes
=> Additional changes to MTA 5.1.1 release notes

docs/cli-guide_5/master.adoc, docs/getting-started-guide_5/master.adoc, docs/maven-guide_5/master.adoc, docs/plugin-guide_5/master.adoc, docs/release_notes-5.0/master.adoc, docs/rules-development-guide_5/master.adoc, docs/topics_5/making-open-source-more-inclusive.adoc, docs/web-console-guide_5/master.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2969.
Preview: http://file.emea.redhat.com/rhoch/25012021/inc_web_c/html-single/#making-open-source-more-inclusive_web-console-guide
=> Inclusive language statement for MTA 5.1.1+ documents

docs/maven-guide_5/master.adoc, docs/plugin-guide_5/master.adoc
Previews: http://file.emea.redhat.com/rhoch/27012021/maven/html-single/  and http://file.emea.redhat.com/rhoch/27012021/ide/html-single/
=> Correct installation files for Maven and IDE

docs/topics_5/installing-web-console-on-openshift.adoc, docs/web-console-guide_5/master.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3008
Preview: http://file.emea.redhat.com/rhoch/16022021/ocpheadings/html-single/#installing_the_web_console_on_openshift_container_platform
=> Web console guide: updating OCP version for Operator

docs/release_notes-5.1/master-docinfo.xml, docs/release_notes-5.1/master.adoc, docs/topics_5/rn-new-features.adoc
https://issues.redhat.com/browse/WINDUP-2997?focusedCommentId=15802358&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15802358
Preview build: http://file.tlv.redhat.com/~apinnick/update-rn_release_notes-5.1/
=> update 5.1.2 release notes

docs/topics/rn-known-issues.adoc, docs/topics/rn-new-features.adoc, docs/topics/rn-resolved-issues.adoc, docs/topics/templates/document-attributes.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3045
Preview: http://file.emea.redhat.com/rhoch/01042021/514rn/html-single/
=> MTA 5.1.4 release notes

docs/plugin-guide/master.adoc, docs/topics/about-cli.adoc, docs/topics/cli-args.adoc, docs/topics/maven-arguments.adoc, docs/topics/plugin-components.adoc, docs/topics/plugin-create-config.adoc, docs/topics/web-adding-global-custom-labels.adoc, docs/topics/web-adding-global-custom-rules.adoc, docs/topics/what-is-the-toolkit.adoc, docs/vs-code-plugin-guide/master.adoc
MTA 5.1.4
Incorporates Ramon Roman Nissan's suggested changes to the "About the Migration Toolkit for Applications" section of MTA documents. (https://docs.google.com/document/d/1hIBO3U-AYoJq4xssqsxODNAXzQxocUGqDTCrGfU9Fn8/edit#heading=h.iq9pnrek69xu)
Preview: https://deploy-preview-436--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#what-is-the-toolkit_web-console-guide
=> Changes to "About the Migration Toolkit for Applications"

docs/topics/rn-known-issues.adoc, docs/topics/rn-resolved-issues.adoc
MTA 5.2
Partially resolves: https://issues.redhat.com/browse/WINDUP-3069
Preview: https://deploy-preview-448--windup-documentation.netlify.app/docs/release-notes/release_notes-5.2/master/index.html#rn-known-issues_release-notes
=> WIP MTA 5.2 known and resolved issues

docs/topics/rn-resolved-issues.adoc
MTA 5.2.1
Partially resolves https://issues.redhat.com/browse/WINDUP-3196 (resolved issues).
Preview:  https://deploy-preview-471--windup-documentation.netlify.app/docs/release-notes/master/index.html#rn-resolved-issues_release-notes 
Note that version number will be corrected in this and all PRs in a separate PR that adjusts all version numbers in the document set.
=> MTA 5.2.1 release notes: resolved issues

docs/topics/rn-new-features.adoc
MTA version 5.2.1.
Partially resolves: https://issues.redhat.com/browse/WINDUP-3196 (New features)
Preview: https://deploy-preview-458--windup-documentation.netlify.app/docs/release-notes/master/index.html#rn-new-features_release-notes
=> MTA 5.2.1 release notes: new features

docs/topics/cli-run.adoc, docs/topics/using-openrewrite-recipes.adoc, website/docs/cli-guide/master.adoc, website/docs/cli-guide/master.html, website/docs/eclipse-code-ready-studio-guide/master.html, website/docs/getting-started-guide/master.html, website/docs/maven-guide/master.html, website/docs/release-notes/master.html, website/docs/rules-development-guide/master.html, website/docs/topics/proc_cli-execute.adoc, website/docs/topics/rn-new-features.adoc, website/docs/vs-code-extension-guide/master.html, website/docs/web-console-guide/master.html, website/index.md
MTA 5.2.1.
Resolves https://issues.redhat.com/browse/WINDUP-3214.
Preview: http://file.emea.redhat.com/rhoch/06122021/openrewrite/html-single/#using-openrewrite-recipes_cli-guide (section 2.2.4 only)
=> OpenRewrite description for MTA CLI guide

docs/topics/web-openshift-insufficient-resources.adoc
https://issues.redhat.com/browse/WINDUP-3272
https://deploy-preview-520--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#troubleshooting-a-web-console-installation-on-openshift
=> WINDUP-3272 Amending a procedure module in accordance with the procedure template

docs/topics/templates/document-attributes.adoc
Bug fix
Fixes broken link in _Introduction to the Migration Toolkit for Applications_ .
Preview:
=> Fix broken link in Intro to MTA

docs/topics/using-openrewrite-recipes.adoc
New feature.
MTA 5.3.0
Resolves: https://issues.redhat.com/browse/WINDUP-3254
Preview: https://deploy-preview-523--windup-documentation.netlify.app/docs/cli-guide/master/index.html#using-openrewrite-recipes_cli-guide
=> New OpenRewrite parameter

docs/topics/using-openrewrite-recipes.adoc
PR #523 is for MTA 5.3 only, which I accidentallymerged. This PR reverts windup/windup-documentation#523
=> Revert "New OpenRewrite parameter"

docs/topics/rn-new-features.adoc
MTA 5.3.0
Partially resolves https://issues.redhat.com/browse/WINDUP-3340
Preview: https://deploy-preview-534--windup-documentation.netlify.app/docs/release-notes/master/index.html#rn-new-features_release-notes The version number will be correct when we merge all PRs.
=> RTM: MTA 5.3.0 Release notes: new features

docs/topics/rn-resolved-issues.adoc
MTA 5.3.0
Partially resolves https://issues.redhat.com/browse/WINDUP-3340
This is the "Resolved issues" section of the release notes.
Preview: https://deploy-preview-532--windup-documentation.netlify.app/docs/release-notes/master/index.html#rn-resolved-issues_release-notes
=> Resolved issues for MTA 5.3.0 release notes

docs/topics/using-openrewrite-recipes.adoc
MTV 5.3
Resolves: https://issues.redhat.com/browse/WINDUP-3254
The contents of this PR were merged by mistake and that merge was reverted. This is the PR that needs to be merged to MTA 5.3.0
=> New OpenRewrite option

docs/topics/cli-args.adoc, docs/topics/maven-arguments.adoc, docs/topics/web-create-project.adoc
MTV 5.3.0
Resolves https://issues.redhat.com/browse/WINDUP-3257
Add information about the new advanced option, analyzeKnownLibraries, to the MTA documentation. 
Previews: 
1. Web console guide https://deploy-preview-529--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#web-create-project_ocp-42 [right before step 16]. 
2. CLI guide: https://deploy-preview-529--windup-documentation.netlify.app/docs/cli-guide/master/index.html#cli-args_cli-guide [Third item in table]. 
3. Maven plugin guide: https://deploy-preview-529--windup-documentation.netlify.app/docs/maven-guide/master/index.html#maven-arguments_maven-guide [First item in table].
=> WINDUP-3257: analyzeKnownLibraries

docs/topics/vs-code-extension-run-configuration.adoc
MTV 5.3.0
Resolves: https://issues.redhat.com/browse/WINDUP-3369 by making the suggested additions to the run configuration procedure. 
Preview: https://deploy-preview-539--windup-documentation.netlify.app/docs/vs-code-extension-guide/master/index.html#vs-code-extension-run-configuration_vsc-extension-guide
=> VSCode extension: Improvements to configuration procedure

docs/topics/web-create-project.adoc
MTA 5.4+
Resolves: https://issues.redhat.com/browse/WINDUP-3385
Preview: https://deploy-preview-541--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#web-create-project_ocp-42 [Description of "Allow network access" near end of the procedure].
=> WINDUP-3385: Change description of "Allow network access" advanced option

docs/web-console-guide/master.adoc, index.md
Revises the master.adoc file for use with the MTA UI guide.
=> Revised master.adoc for MTA 6.0 UI guide

docs/topics/mta-6-installing-web-console-on-openshift.adoc, docs/web-console-guide/master.adoc
MTA 6.0
Installation instructions for the MTA 6.0 UI
Resolves: https://issues.redhat.com/browse/TACKLE-869
Preview: https://deploy-preview-581--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-6-installing-web-console-on-openshift_web-console-guide
=> UI install

docs/topics/mta-web-administrator-view.adoc, docs/web-console-guide/master.adoc
MTA 6.0 
Resolves: https://issues.redhat.com/browse/TACKLE-806
Preview: https://deploy-preview-561--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-administration-view_ocp-42
=> Tackle-806:  Admin perspective for MTA 6.0

docs/cli-guide/master.adoc, docs/eclipse-code-ready-studio-guide/master.adoc, docs/getting-started-guide/master-docinfo.xml, docs/getting-started-guide/master.adoc, docs/maven-guide/master.adoc, docs/topics/about-the-mta-operator.adoc, docs/topics/about-the-user-interface.adoc, docs/topics/about-the-web-console.adoc, docs/topics/about-tools.adoc, docs/topics/getting-started-about-ide-addons.adoc, docs/topics/migration-paths.adoc, docs/topics/mta-about-console-guide.adoc, docs/topics/mta-about-the-intro-to-mta-guide.adoc, docs/topics/mta-what-is-the-toolkit.adoc, docs/topics/new-mta-features.adoc, docs/topics/templates/document-attributes.adoc, docs/vs-code-extension-guide-mtr/master.adoc, docs/web-console-guide/master.adoc
Rewrite of Introduction to Migration Toolkit for Applications; revision of introduction to the UI guide.
Resolves https://issues.redhat.com/browse/WINDUP-3427 and https://issues.redhat.com/browse/TACKLE-857
Previews:
1. https://deploy-preview-573--windup-documentation.netlify.app/docs/getting-started-guide/master/index.html  Introduction to Migration Toolkit for Applications (complete)
2. https://deploy-preview-573--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-about-console-guide_web-console-guide Intro to the User Interface guide, using the new language for MTA.  The rest of the UI is fixed in other PRs. I just want you to check the new intro.
=> Revised Intro to MTA 

docs/topics/mta-web-config-git-rep.adoc, docs/web-console-guide/master.adoc
MTA 6.0
Resolves: https://issues.redhat.com/browse/TACKLE-805
Preview: https://deploy-preview-565--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#configuring-git-repositories
=> Tackle -805: Git configuration for MTA 6.0

docs/topics/mta-web-subv-rep.adoc, docs/web-console-guide/master.adoc
MTA 6.0
Resolves: https://issues.redhat.com/browse/TACKLE-804
Preview: https://deploy-preview-564--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-subv-rep_ocp-42
=> Tackle-804 Subversion configuration for MTA 6.0

docs/topics/mta-web-config-maven-rep.adoc, docs/web-console-guide/master.adoc
MTA 6.0
Resolves: https://issues.redhat.com/browse/TACKLE-803
Preview: https://deploy-preview-563--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-config-maven-rep_ocp-42
=> Tackle-803: Maven configuration for MTA 6.0

docs/topics/mta-web-applying-assessments-to-other-apps.adoc, docs/topics/mta-web-assessing-apps.adoc, docs/topics/mta-web-configuring-and-running-an-application-analysis.adoc, docs/topics/mta-web-reviewing-an-analysis-report.adoc, docs/web-console-guide/master.adoc
MTA 6.0
Resolves https://issues.redhat.com/browse/TACKLE-798
Preview: https://deploy-preview-566--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#assessing-and-analyzing-applications
=> MTA 6.0 UI -- Bulk Analysis Configuration 

docs/topics/mta-web-about-adding-applications.adoc, docs/topics/mta-web-assigning-application-credentials.adoc, docs/topics/mta-web-creating-applications.adoc, docs/topics/mta-web-downloading-app-list-template.adoc, docs/topics/mta-web-importing-an-app-list.adoc, docs/web-console-guide/master.adoc
MTA 6.0 
Resolves: https://issues.redhat.com/browse/TACKLE-801
Preview:https://deploy-preview-559--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#adding-applications
=> TACKLE-801: Assign Credentials to Applications for MTA 6.0

docs/intellij-idea-plugin-guide/master.adoc, docs/plugin-guide/master.adoc, docs/topics/mta-6-installing-web-console-on-openshift.adoc, docs/topics/mta-about-console-guide.adoc, docs/topics/mta-web-adding-applications.adoc, docs/topics/mta-web-administrator-view.adoc, docs/topics/mta-web-application-attributes.adoc, docs/topics/mta-web-config-maven-credentials.adoc, docs/topics/mta-web-config-proxy-credentials.adoc, docs/topics/mta-web-config-source-control-credentials.adoc, docs/topics/mta-web-downloading-app-list-template.adoc, docs/topics/mta-web-importing-an-app-list.adoc, docs/web-console-guide/master.adoc, index.md, website/docs/topics/proc_cli-execute.adoc
test of UI Guide. Note -- includes reference to Developer view which is not yet documented.
=> First build of UI guide

docs/release-notes/master-docinfo.xml, docs/release-notes/release_notes-6.0/master.adoc, docs/topics/mta-rn-known-issues.adoc, docs/topics/mta-rn-new-features.adoc, docs/topics/mta-rn-resolved-issues.adoc
MTA 6.0
Resolves https://issues.redhat.com/browse/TACKLE-812
Preview (https://deploy-preview-578--windup-documentation.netlify.app/docs/release-notes/master/index.html)
=> Release notes MTA 6.0

docs/eclipse-code-ready-studio-guide-mtr/master.adoc, docs/maven-guide-mtr/master.adoc, docs/release-notes-mtr/topics/what-is-the-toolkit.adoc, docs/rules-development-guide-mtr/master.adoc, docs/topics/about-maven.adoc, docs/topics/get-involved.adoc, docs/topics/important-links.adoc, docs/topics/maven-arguments.adoc, docs/topics/maven-multi-module.adoc, docs/topics/maven-run.adoc, docs/topics/templates/document-attributes.adoc, docs/topics/what-is-the-toolkit.adoc
WINDUP-3434: Rebranding to MTR - Maven Plugin Guide
Resolves: https://issues.redhat.com/browse/WINDUP-3434
MTR 1.0
=> WINDUP-3434: Rebranding to MTR - Maven Plugin Guide

docs/cli-guide-mtr/master-docinfo.xml, docs/cli-guide/master-docinfo.xml, docs/getting-started-guide/master-docinfo.xml, docs/web-console-guide-mtr/master-docinfo.xml, docs/web-console-guide/master-docinfo.xml
Reverts windup/windup-documentation#599
=> Revert "update subtitles"

docs/cli-guide-mtr/master.adoc, docs/topics/intellij-idea-plugin-run-configuration.adoc
WINDUP-3438: Developers web site IntelliJ documentation link
Resolves: https://issues.redhat.com/browse/WINDUP-3438
MTR 1.0
=> WINDUP-3438: Developers web site IntelliJ documentation link

docs/maven-guide-mtr/master.adoc, docs/topics/add-rule-to-mtr.adoc, docs/topics/important-links.adoc, docs/topics/rules-important-links.adoc
Windup_3434_fix2
Fixes https://github.com/windup/windup-documentation/pull/610
MTR 1.0
=> Windup_3434_fix2

docs/cli-guide-mtr/master.adoc, docs/topics/templates/document-attributes.adoc
=> Windup_3432_fix

docs/topics/about-the-user-interface.adoc, docs/topics/execute.adoc, docs/topics/web-adding-custom-rules.adoc, docs/topics/what-is-the-toolkit.adoc, docs/web-console-guide-mtr/master.adoc
=> Windup 3487 fix2

docs/topics/vs-code-extension-interface.adoc, docs/topics/vs-code-extension-run-configuration.adoc, docs/vs-code-extension-guide/master.adoc
=> Fixes VS Code extension guide links

docs/topics/intellij-idea-plugin-run-configuration.adoc, docs/topics/vs-code-extension-run-configuration.adoc
Corrections to MTR 1.0 documentation
=> MTR_1_0_corrections

docs/topics/web-create-project.adoc
MTR 1.0 
Resolves https://issues.redhat.com/browse/WINDUP-3386
https://deploy-preview-543--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#web-create-project_ocp-42
The update is in section 3.1 at the end of step 15
=> Transaction analysis WEB

docs/topics/maven-arguments.adoc
MTR 1.0 
Resolves https://issues.redhat.com/browse/WINDUP-3387?filter=-3 preview
https://deploy-preview-542--windup-documentation.netlify.app/docs/maven-guide/master/index.html#maven-arguments_maven-guide
The update is in Appendix A: Reference material Table A1, Argument (enableTransactionAnalysis)
=> Transaction analysis MAVIN

docs/topics/mta-web-seeding-instances.adoc, docs/web-console-guide/master.adoc
MTA 6.0 
Resolves https://issues.redhat.com/browse/TACKLE-873
Preview https://deploy-preview-624--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-seeding-instances_user-interface-guide
=> Tackle-873 Seeding instances

docs/topics/about-the-mta-operator.adoc
MTA 6.0
Fixes incorrect attribute in section 5.1 of _Introduction to the Migration toolkit for Applications_.
Preview: https://deploy-preview-636--windup-documentation.netlify.app/docs/getting-started-guide/master/index.html#about-the-mta-operator_getting-started-guide
=> Fix incorrect attribute

.gitignore, .idea/windup-documentation.iml, docs/cli-guide-mtr/master.adoc, docs/cli-guide/master.adoc, docs/topics/available-openrewrite-recipes.adoc, docs/topics/using-openrewrite-recipes.adoc
MTR 1.0, MTA 6.0
Resolves: https://issues.redhat.com/browse/WINDUP-3579
Preview:
MTA: https://deploy-preview-640--windup-documentation.netlify.app/docs/cli-guide/master/index.html#using-openrewrite-recipes_cli-guide
MTR: https://deploy-preview-640--windup-documentation.netlify.app/docs/cli-guide-mtr/master/index.html#using-openrewrite-recipes_cli-guide
=> Windup-3579: MTA/MTR CLI guides using OpenRewrite recipes

docs/topics/installing-web-console-on-openshift.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3599
MTR 1.0.0
Preview: https://deploy-preview-642--windup-documentation.netlify.app/docs/web-console-guide-mtr/master/index.html#installing-web-console-on-openshift_web-console-guide
=> MTR Web Console on Openshift Prerequisites

docs/release-notes-mtr/master-docinfo.xml
MTR 1.0.1
Changes abstract of release notes to include version 1.0.1
=> fix abstract

docs/topics/mta-6-installing-web-console-on-openshift.adoc
MTA Version 6.0
Resolves - https://issues.redhat.com/browse/TACKLE-913
Preview - https://deploy-preview-641--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#memory-testing-requirements-migration-toolkit-for-applications-user-interface
=> Tackle- 913 Memory testing

docs/topics/about-maven.adoc, docs/topics/mta-6-installing-web-console-on-openshift.adoc
Resolves: https://issues.redhat.com/browse/MTA-47
MTA 6.0.1
Preview: https://deploy-preview-651--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#persistent-volume-requirements
=> MTA-47: Installation instructions

docs/topics/mta-6-installing-web-console-on-openshift.adoc
Resolves: https://issues.redhat.com/browse/MTA-45
MTA 6.0
Preview: https://deploy-preview-650--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#installing-the-migration-toolkit-for-applications-operator-and-the-user-interface
=> MTA-45: Operator updated options

docs/topics/mta-6-installing-web-console-on-openshift.adoc, docs/topics/mta-web-config-maven-repo-size.adoc, docs/topics/mta-web-config-maven-repo.adoc
Resolves: https://issues.redhat.com/browse/MTA-46
MTA 6.0.1
Preview: https://deploy-preview-655--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#configuring-maven-repositories
=> MTA-46: Maven configuration changes

docs/topics/mta-6-installing-web-console-on-openshift.adoc
MTA 6.0.0, 6.0.1
Resolves - https://issues.redhat.com/browse/TACKLE-947
Preview - https://deploy-preview-660--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#red-hat-single-sign-on
=> Tackle-947 RHSSO

docs/release-notes-mtr/master.adoc, docs/topics/mtr-rn-known-issues-1_0_2.adoc, docs/topics/mtr-rn-new-features-1_0_2.adoc, docs/topics/mtr-rn-resolved-issues-1_0_2.adoc, method-discover.adoc
Created new Release Notes for MTR 1.0.2
1 New Feature in version numbered file.
Links to Known Issues and Resolved Issues in new version numbered files.
=> Windup 3661 mtr1 0 2rn hvider

docs/topics/templates/document-attributes.adoc
Replaces https://github.com/windup/windup-documentation/pull/664/files#diff-5c34f2f0b2e21abed8e1bd63489ae12d660c467b39b572bfaa228cce0cebc542
Resolves: https://issues.redhat.com/browse/WINDUP-3660
Preview:
=> WINDUP-3660

docs/topics/mta-web-downloading-an-analysis-report.adoc, docs/topics/mta-web-reviewing-an-analysis-report.adoc, docs/web-console-guide/master.adoc
Resolves: https://issues.redhat.com/browse/MTA-139
MTA 6.1.0
Preview: https://deploy-preview-672--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-downloading-an-analysis-report_user-interface-guide
=> MTA-139: Download HTML and CSV analysis reports

docs/topics/mta-web-configuring-and-running-an-application-analysis.adoc, docs/topics/mta-web-tagging-an-application.adoc, docs/web-console-guide/master.adoc
Resolves: https://issues.redhat.com/browse/MTA-142
MTA 6.1.0
Preview:
https://deploy-preview-675--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-configuring-and-running-an-application-analysis_user-interface-guide  (Step 14)
https://deploy-preview-675--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-tagging-an-application_user-interface-guide
=> MTA-142: Automated tagging of resources

docs/topics/installing-web-console-on-openshift.adoc, docs/topics/mta-6-installing-web-console-on-openshift.adoc, docs/topics/mta-web-adding-applications.adoc, docs/topics/mta-web-administration-view.adoc, docs/topics/mta-web-applying-assessments-to-other-apps.adoc, docs/topics/mta-web-assessing-apps.adoc, docs/topics/mta-web-assigning-application-credentials.adoc, docs/topics/mta-web-config-git-rep.adoc, docs/topics/mta-web-config-git-repos.adoc, docs/topics/mta-web-config-http-https-proxy.adoc, docs/topics/mta-web-config-maven-credentials.adoc, docs/topics/mta-web-config-maven-rep.adoc, docs/topics/mta-web-config-maven-repo-size.adoc, docs/topics/mta-web-config-maven-repo.adoc, docs/topics/mta-web-config-proxy-credentials.adoc, docs/topics/mta-web-config-source-control-credentials.adoc, docs/topics/mta-web-config-subversion-repos.adoc, docs/topics/mta-web-downloading-app-list-template.adoc, docs/topics/mta-web-importing-an-app-list.adoc, docs/topics/mta-web-proxy-config.adoc, docs/topics/mta-web-reviewing-an-analysis-report.adoc, docs/topics/mta-web-seeding-instances.adoc, docs/topics/mta-web-subv-rep.adoc, docs/topics/new-mta-features.adoc, docs/web-console-guide/master.adoc
Resolves: https://issues.redhat.com/browse/MTA-141
MTA-6.1.0
Preview:
https://deploy-preview-669--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-6-ui-interface-views
and throughout the MTA documentation
=> MTA-141 Renaming web console components 

docs/topics/mta-6-installing-web-console-on-openshift.adoc
[MTA-451](https://issues.redhat.com/browse/MTA-451)
PR submitted on behalf of @HagayVider1, who wants to add a subsection for Eviction threshold
=> MTA-451 Adding a section for Eviction threshold

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-6-1-1.adoc, docs/topics/mta-rn-new-features-6-1-1.adoc, docs/topics/mta-rn-resolved-issues-6-1-1.adoc
First draft for [MTA 523](https://issues.redhat.com/browse/MTA-523)
=> MTA-523 Release Notes for 6.1.1

docs/topics/cli-args.adoc, docs/topics/web-create-project.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3701
MTR 1.1.0
Preview:
https://deploy-preview-694--windup-documentation.netlify.app/docs/cli-guide-mtr/master/index.html#cli-args_cli-guide
https://deploy-preview-694--windup-documentation.netlify.app/docs/web-console-guide-mtr/master/index.html#web-create-project_web-console-guide
=> WINDUP-3701 Doc - Analysis summary extract

docs/topics/installing-web-console-on-openshift.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3733
MTR 1.1.0
Preview:
https://deploy-preview-689--windup-documentation.netlify.app/docs/web-console-guide-mtr/master/index.html#installing-web-console-on-openshift_web-console-guide
=> WINDUP-3733 MTR Web UI Guide - OpenShift Prerequisites

docs/topics/cli-args.adoc, docs/topics/web-create-project.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3786
MTR 1.1.0
Preview:
https://deploy-preview-691--windup-documentation.netlify.app/docs/cli-guide-mtr/master/index.html#cli-args_cli-guide
https://deploy-preview-691--windup-documentation.netlify.app/docs/web-console-guide-mtr/master/index.html#web-create-project_web-console-guide
=> WINDUP-3786 New advanced option to export Reports as a zip

docs/topics/maven-run.adoc, docs/topics/snippet_jdk-hardware-mac-prerequisites.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3737
MTR 1.1.0
Preview: 
https://deploy-preview-688--windup-documentation.netlify.app/docs/maven-guide-mtr/master/index.html#maven-run_maven-guide
=> WINDUP-3737: MTR Maven Plugin - Compatibility with Java 17

docs/topics/web-review-reports.adoc
https://issues.redhat.com/browse/WINDUP-3700
MTR 1.1.0
Preview:
=> WINDUP-3700 fix

docs/topics/about-cli.adoc, docs/topics/about-tools.adoc, docs/topics/method-discover.adoc, docs/topics/migration-paths.adoc, docs/topics/mtr-rn-new-features-1_1_0.adoc, docs/topics/mtr-rn-resolved-issues-1_1_0.adoc, docs/topics/what-is-the-toolkit.adoc
Michael and Andy worked through the MTR 1.1.0 docs and made small changes
=> Updating MTR 1.1.0 docs with small corrections

docs/topics/what-is-the-toolkit.adoc
=> Typo: applicatons

docs/topics/mta-web-creating-custom-migration-targets.adoc
Resolves: https://issues.redhat.com/browse/MTA-556
MTA 6.1.0+
Preview: https://deploy-preview-704--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-creating-custom-migration-targets_user-interface-guide
=> MTA-556 Docs Improvement - Custom Migration Targets (RuleSets)

docs/topics/mta-web-tagging-an-application.adoc
Resolves: https://issues.redhat.com/browse/MTA-557
MTA 6.1.0+
Preview: 
https://deploy-preview-705--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-tagging-an-application_user-interface-guide
=> MTA-557 Docs Improvement - Automated tagging of resources

docs/topics/templates/document-attributes.adoc
https://issues.redhat.com/browse/WINDUP-3947
Updating attributes for MTR 1.1.1
:ProductVersion: 1.1.1
:PluginName: MTR plugin
:ProductDistributionVersion: 1.1.1.GA-redhat-00001
:ProductDistribution: mtr-1.1.1.GA-offline
=> WINDUP-3947: Attributes updates MTR 1.1.1

docs/topics/mtr-rn-resolved-issues-1_1_1.adoc
Updating filter for release notes MTR 1.1.1
Direct preview: https://deploy-preview-710--windup-documentation.netlify.app/docs/release-notes-mtr/master/index.html#mtr-rn-resolved-issues-111_release-notes
=> changing filter for MTR 1.1.1 release notes

docs/release-notes/master.adoc, docs/topics/mta-rn-cgo-release-6-1-2.adoc
https://issues.redhat.com/browse/MTA-824
adding release notes for cgo release
=> MTA-824: release notes, adding cgo-release doc and updating master

docs/topics/templates/document-attributes.adoc
https://issues.redhat.com/browse/MTA-825
Adding attributes for MTA 6.1.2
:ProductVersion: 6.1.2
:PluginName: MTA plugin
:MavenProductVersion: 6.1.2.GA-redhat-00001
:ProductDistributionVersion: 6.1.2.GA-redhat
:ProductDistribution: mta-6.1.2-cli-offline.zip
=> MTA-825: updating attributes for 6.1.2

docs/topics/mta-6-installing-web-console-on-openshift.adoc
MTA-451: Users adjust Windup Addon Requests and Add Limits: advising customers to implement eviction thresholds to protect their nodes
MTA 6.1.1
Preview:
https://deploy-preview-714--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#installing-the-migration-toolkit-for-applications-operator-and-the-user-interface
https://deploy-preview-714--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#eviction-threshold_user-interface-guide
=> MTA-451 (reopened)

docs/topics/mta-web-adding-applications.adoc, docs/topics/mta-web-application-attributes.adoc, docs/topics/mta-web-creating-jira-issues-for-migration-wave.adoc, docs/topics/mta-web-creating-migration-waves.adoc, docs/web-console-guide/master.adoc
Resolves: https://issues.redhat.com/browse/MTA-546
MTA 6.2.0
Preview:
https://deploy-preview-711--windup-documentation.netlify.app/docs/web-console-guide/master/#mta-web-creating-migration-waves_user-interface-guide
https://deploy-preview-711--windup-documentation.netlify.app/docs/web-console-guide/master/#mta-web-creating-jira-issues-for-migration-wave_user-interface-guide
https://deploy-preview-711--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-application-attributes_user-interface-guide
=> MTA-546: Migration Waves

docs/topics/mta-web-configuring-and-running-an-application-analysis.adoc
Resolves: https://issues.redhat.com/browse/MTA-547
MTA 6.2.0
Preview: https://deploy-preview-718--windup-documentation.netlify.app/docs/web-console-guide/master/#viewing-analysis-details_user-interface-guide
=> MTA-547: Document: Presenting data in more readable format

docs/topics/mta-web-downloading-an-analysis-report.adoc
MTA 6.2.0
Resolves https://issues.redhat.com/browse/MTA-1117 by specifying the filename of the downloaded application report.
Preview: https://deploy-preview-719--windup-documentation.netlify.app/docs/web-console-guide/master/#mta-web-downloading-an-analysis-report_user-interface-guide
=> The application report filename is report.tar.gz when downloaded

docs/topics/templates/document-attributes.adoc
6.2.0 the version should be : 6.2.0.GA-redhat-00002
=> MTA-1115: Attributes Update

docs/topics/mta-web-config-jira-credentials.adoc, docs/topics/mta-web-create-config-jira-connection.adoc, docs/web-console-guide/master.adoc
Resolves: https://issues.redhat.com/browse/MTA-551
MTA 6.2.0
Preview:
https://deploy-preview-712--windup-documentation.netlify.app/docs/web-console-guide/master/#creating-configuring%20jira-connection
https://deploy-preview-712--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-6-ui-interface-views
=> MTA-551: Integration with Jira

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-6-2-0.adoc, docs/topics/mta-rn-new-features-6-2-0.adoc, docs/topics/mta-rn-resolved-issues-6-2-0.adoc
Updating release notes for MTA 6.2.0
=> MTA-552: Release notes

docs/topics/mta-rn-new-features-6-2-0.adoc, docs/topics/mta-web-config-jira-credentials.adoc
MTA-6.2.0
Preview:
https://deploy-preview-729--windup-documentation.netlify.app/docs/release-notes/master/#rn-new-features-6-2-0_release-notes
=> MTA-6.2.0 xrefs in RN

docs/topics/mta-rn-new-features-6-2-0.adoc
MTA-6.2.0
Preview: https://deploy-preview-730--windup-documentation.netlify.app/docs/release-notes/master/#rn-new-features-6-2-0_release-notes
=> MTA-6.2.0 links in RN

docs/topics/templates/document-attributes.adoc
Updating attributes for MTR 1.2.0
* **:DocInfoProductNumber: 1.2**
* **:ProductVersion: 1.2.0**
* **:ProductDistributionVersion: 1.2.0.GA-redhat-00001**
* **:ProductDistribution: mtr-1.2.0.GA-offline**
=> MTR-3998: Updating Attributes for MTR 1.2.0

docs/release-notes-mtr/master.adoc, docs/topics/mta-rn-new-features-6-2-0.adoc, docs/topics/mtr-rn-known-issues-1-2-0.adoc, docs/topics/mtr-rn-new-features-1-2-0.adoc, docs/topics/mtr-rn-resolved-issues-1-2-0.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3997
MTR 1.2.0
Preview: https://deploy-preview-736--windup-documentation.netlify.app/docs/release-notes-mtr/master/
=> Windup 3997: mtr 1 2 0 release notes hvider

docs/topics/overriding-rules.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3923
MTR 1.2.0
Preview: https://deploy-preview-737--windup-documentation.netlify.app/docs/rules-development-guide/master/#overriding-a-rule
=> WINDUP-3923: Document Rules Override enhancement

docs/topics/fork-ruleset-repo.adoc
Superfluous word removed
MTR 1.2
Preview: https://deploy-preview-753--windup-documentation.netlify.app/docs/rules-development-guide-mtr/master/#review-existing-rules_rules-development-guide-mtr
=> Rules_Development_guide_small_fix2

docs/topics/create-first-xml-rule.adoc
Heading style applied to 2.1.3 of Rules Development guide
MTR 1.2
Preview: https://deploy-preview-752--windup-documentation.netlify.app/docs/rules-development-guide-mtr/master/#creating-the-rule_rules-development-guide-mtr
=> Rules_Development_guide_small_fix

docs/topics/web-updating-an-analysis.adoc
Replacing a wrong screenshot in the Web Console guide
MTR 1.2
Preview: https://deploy-preview-749--windup-documentation.netlify.app/docs/web-console-guide-mtr/master/#web-updating-an-analysis_web-console-guide
=> Web_Console_screenshot_fix

docs/topics/templates/document-attributes.adoc
@anarnold97 created attribute as requested.
=> Updating attributes to include full name

docs/topics/csv-export.adoc, docs/topics/get-involved.adoc, docs/topics/maven-arguments.adoc, docs/topics/maven-multi-module.adoc
MTR 1.2.0
Resolves - https://issues.redhat.com/browse/WINDUP-4046
Deploy preview - https://deploy-preview-755--windup-documentation.netlify.app/docs/maven-guide-mtr/master/#csv-export_maven-guide
https://deploy-preview-755--windup-documentation.netlify.app/docs/maven-guide-mtr/master/#maven-multi-module_maven-guide
https://deploy-preview-755--windup-documentation.netlify.app/docs/maven-guide-mtr/master/#maven-arguments_maven-guide
https://deploy-preview-755--windup-documentation.netlify.app/docs/maven-guide-mtr/master/#get-involved_maven-guide
https://deploy-preview-755--windup-documentation.netlify.app/docs/maven-guide-mtr/master/#maven-target-argument_maven-guide
=> Windup 4046

docs/release-notes-mtr/master.adoc, docs/topics/mtr-rn-known-issues-1-2-1.adoc, docs/topics/mtr-rn-resolved-issues-1-2-1.adoc
* [WINDUP-4058](https://issues.redhat.com/browse/WINDUP-4058)
* [Release notes MTR 1.2.1](https://deploy-preview-765--windup-documentation.netlify.app/docs/release-notes-mtr/master/#mtr-1-2-1)
=> WINDUP-4058: Release Notes for MTR 1.2.1

docs/topics/templates/document-attributes.adoc
[WINDUP-4059](https://issues.redhat.com/browse/WINDUP-4059)
Updated attributes for MTR 1.2.1:
```
:ProductVersion: 1.2.1
:PluginName: MTR plugin
:ProductDistributionVersion: 1.2.1.GA-redhat-00001
:ProductDistribution: mtr-1.2.1.GA-offline
```
* There is no documentation preview available
=> WINDUP-4059: Attributes Update MTR-1.2.1

docs/topics/templates/document-attributes.adoc
* [WINDUP-4076](https://issues.redhat.com/browse/WINDUP-4076)
[1.2.2 rendered in docs](https://deploy-preview-772--windup-documentation.netlify.app/docs/cli-guide-mtr/master/#tech-tags_cli-guide)
```
:ProductVersion: 1.2.2
...
:ProductDistributionVersion: 1.2.2.GA-redhat-00001
:ProductDistribution: mtr-1.2.2.GA-offline
```
=> WINDUP-4076: Attributes update for 1.2.2

docs/release-notes-mtr/master.adoc, docs/topics/mtr-rn-known-issues-1-2-2.adoc, docs/topics/mtr-rn-resolved-issues-1-2-2.adoc
[WINDUP-4075](https://issues.redhat.com/browse/WINDUP-4075)
[MTR 1.2.2 release notes](https://deploy-preview-770--windup-documentation.netlify.app/docs/release-notes-mtr/master/#mtr-1-2-2)
* [WINDUP-4053](https://issues.redhat.com/browse/WINDUP-4053)
* [WINDUP-4072](https://issues.redhat.com/browse/WINDUP-4072)
=> WINDUP-4075: Release notes for MTR 1.2.2

docs/topics/about-the-mta-operator.adoc, docs/topics/mta-6-installing-web-console-on-openshift.adoc, docs/topics/mta-web-seeding-instances.adoc
* [MTA-1938](https://issues.redhat.com/browse/MTA-1938)
* [Installing the Migration Toolkit for Applications user interface](https://deploy-preview-790--windup-documentation.netlify.app/docs/web-console-guide/master/#mta-6-installing-web-console-on-openshift_user-interface-guide)
* [Seeding an instance](https://deploy-preview-790--windup-documentation.netlify.app/docs/web-console-guide/master/#mta-web-seeding-instances_user-interface-guide)
=> MTA-1938: Formatting errors in MTA documentation

docs/topics/mta-web-creating-jira-issues-for-migration-wave.adoc
https://issues.redhat.com/browse/MTA-1616
Add note to User Interface Guide > Creating Jira issues for a migration wave 
regarding new "unlink from JIRA" option
target file: docs/topics/mta-web-creating-jira-issues-for-migration-wave.adoc
=> MTA-1616 note regarding unlink from JIRA option

docs/topics/mta-web-downloading-an-analysis-report.adoc
Resolves: https://issues.redhat.com/browse/MTA-548
MTA-6.2.0
Preview:
https://deploy-preview-716--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-downloading-an-analysis-report_user-interface-guide
=> MTA-548: Document: Report file should be downloaded with the application name as the filename

docs/topics/migration-paths.adoc
* [MTA-2108](https://issues.redhat.com/browse/MTA-2108)
* [Supported migration paths](https://deploy-preview-810--windup-documentation.netlify.app/docs/getting-started-guide/master/#migration-paths_getting-started-guide)
=> MTA-2108: Update Supported migration paths

docs/topics/templates/document-attributes.adoc
* [MTA-1181](https://issues.redhat.com/browse/MTA-1181)
```
:DocInfoProductNumber: 7.0
:ProductShortName: MTA
...
:ProductVersion: 7.0,0
...
:ProductDistributionVersion: 7.0.0.GA-redhat
:ProductDistribution: mta-7.0.0.GA-cli-offline.zip
```
=> MTA-1181: Attributes Update MTA 7.0.0

docs/topics/mta-rn-known-issues-7-0-0.adoc, docs/topics/mta-rn-resolved-issues-7-0-0.adoc, docs/topics/mta-rn-technical-changes-7-0-0.adoc
* [MTA-2157](https://issues.redhat.com/browse/MTA-2157)
* [Release notes MTA 7.0.0](https://deploy-preview-823--windup-documentation.netlify.app/docs/release-notes/master/#mta-7-0-0)
=> MTA-2157: Issues in Release Notes

docs/release-notes-mtr/master.adoc, docs/topics/mtr-rn-known-issues-1-2-4.adoc, docs/topics/mtr-rn-new-features-1-2-4.adoc, docs/topics/mtr-rn-resolved-issues-1-2-4.adoc
* [WINDUP-4113](https://issues.redhat.com/browse/WINDUP-4113)
=> WINDUP-4113: MTR release notes 1.2.4

docs/topics/about-home-var.adoc, docs/topics/installing-cli-tool.adoc, docs/topics/installing-web-console-or-cli-tool.adoc, docs/topics/mta-about-home-var.adoc
Resolves: https://issues.redhat.com/browse/MTA-2176
MTA 7.0.1
Preview:
=> MTA-2176: Remove "LC_PSN"

docs/topics/templates/document-attributes.adoc, docs/topics/templates/revision-info.adoc
* [MTA-2163](https://issues.redhat.com/browse/MTA-2163)
Removed some line breaks to improve the *Revised on 2024-01-30 21:40:25 UTC in section*
Changed issues report to `https://issues.redhat.com/projects/MTA/issues` 
* [A.1.3. Reporting issues](https://deploy-preview-831--windup-documentation.netlify.app/docs/getting-started-guide/master/#reporting-issues)
=> MTA-2163: Improvements to Introduction to MTA

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-7-0-1.adoc, docs/topics/mta-rn-resolved-issues-7-0-1.adoc, docs/topics/mta-rn-upgrade-notes-7-0-0.adoc, docs/topics/mta-rn-upgrade-notes-7-0-1.adoc
* [MTA-2164 - Release Notes 7.0.1](https://issues.redhat.com/browse/MTA-2164)
* [Release notes MTA-7-0-1](https://deploy-preview-825--windup-documentation.netlify.app/docs/release-notes/master/#mta-7-0-1)
=> MTA-2164: Release notes for MTA 7.0.1

docs/topics/installing-cli-tool.adoc
* [MTA-2205](https://issues.redhat.com/browse/MTA-2205)
* [2.1. Installing the CLI](https://deploy-preview-849--windup-documentation.netlify.app/docs/cli-guide/master/#installing-cli-tool_cli-guide)
=> MTA-2205 add login to registry.redhat.io

docs/topics/cli-run.adoc, docs/topics/manually-test-rules.adoc, docs/topics/mavenize.adoc, docs/topics/review-reports.adoc
* [MTA-2203](https://issues.redhat.com/browse/MTA-2203)
=> MTA-2203-Fix-MTA-CLI-command

docs/topics/mta-rn-upgrade-notes-7-0-1.adoc
* [MTA-2167](https://issues.redhat.com/browse/MTA-2167)
* [2.3. Upgrade notes](https://deploy-preview-850--windup-documentation.netlify.app/docs/release-notes/master/#mta-rn-upgrade-notes-7-0-1_release-notes)
=> MTA-2167-Upgrade-notes-MTA-7.0.1-enabling-questionnaire

docs/topics/vs-code-extension-resolving-issues.adoc, docs/topics/vs-code-extension-reviewing-issues.adoc
* [MTA-2162](https://issues.redhat.com/browse/MTA-2162)
* [4.1. Reviewing issues](https://deploy-preview-832--windup-documentation.netlify.app/docs/vs-code-extension-guide/master/#vs-code-extension-reviewing-issues_vsc-extension-guide)
* [4.2. Resolving issues](https://deploy-preview-832--windup-documentation.netlify.app/docs/vs-code-extension-guide/master/#vs-code-extension-resolving-issues_vsc-extension-guide)
=> MTA-2162-Remove-Quick-Fix

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-7-0-2.adoc, docs/topics/mta-rn-new-features-7-0-2.adoc, docs/topics/mta-rn-resolved-issues-7-0-2.adoc, docs/topics/mta-rn-upgrade-notes-7-0-2.adoc
* [MTA-2196](https://issues.redhat.com/browse/MTA-2196)
* [MTA-2263](https://issues.redhat.com/browse/MTA-2263)
* [MTA 7-0-2](https://deploy-preview-862--windup-documentation.netlify.app/docs/release-notes/master/#mta-7-0-2)
*  [New features](https://deploy-preview-862--windup-documentation.netlify.app/docs/release-notes/master/#rn-new-features-7-0-2_release-notes)
* [Known issues](https://deploy-preview-862--windup-documentation.netlify.app/docs/release-notes/master/#rn-known-issues-7-0-2_release-notes)
* [Resolved issues](https://deploy-preview-862--windup-documentation.netlify.app/docs/release-notes/master/#mta-rn-resolved-issues-7-0-2_release-notes)
=> MTA-2196: Release Notes for MTA 7.0.2

docs/release-notes-mtr/master.adoc, docs/topics/mtr-rn-known-issues-1-2-5.adoc, docs/topics/mtr-rn-new-features-1-2-5.adoc, docs/topics/mtr-rn-resolved-issues-1-2-5.adoc
* [WINDUP-4149](https://issues.redhat.com/browse/WINDUP-4149)
* [MTR 1.2.5](https://deploy-preview-868--windup-documentation.netlify.app/docs/release-notes-mtr/master/#mtr-1-2-5)
* [New features](https://deploy-preview-868--windup-documentation.netlify.app/docs/release-notes-mtr/master/#rn-new-features-1-2-5_release-notes)
* [Known issues](https://deploy-preview-868--windup-documentation.netlify.app/docs/release-notes-mtr/master/#mtr-rn-known-issues-1-2-5_release-notes)
* [Resolved issues](https://deploy-preview-868--windup-documentation.netlify.app/docs/release-notes-mtr/master/#mtr-rn-resolved-issues-1-2-5_release-notes)
=> WINDUP-4149: MTR 1.2.5 Release Notes

docs/topics/templates/document-attributes.adoc
* [WINDUP-4148](https://issues.redhat.com/browse/WINDUP-4148)
```
:ProductVersion: 1.2.5
...
:ProductDistributionVersion: 1.2.5.GA-redhat-00001
:ProductDistribution: mtr-1.2.5.GA-offline
```
=> WINDUP-4148: Attributes updates for MTR-1.2.5

docs/cli-guide/master.adoc, docs/topics/cli-tool-known-issues.adoc
* [MTA-2314](https://issues.redhat.com/browse/MTA-2314)
* [MTA CLI Known issues](https://deploy-preview-873--windup-documentation.netlify.app/docs/cli-guide/master/#cli-tool-known-issues_cli-guide)
=> MTA-2314: MTA CLI limitations with podman on windows

docs/topics/templates/document-attributes.adoc
* https://issues.redhat.com/browse/MTA-2197[MTA-2197]
=> Updated MTA 7.0.2 document attributes

docs/topics/about-cli.adoc
https://issues.redhat.com/browse/MTA-2787
=> MTA-2787 - Fixing typo in docs/topics/about-cli.adoc

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-6-2-2.adoc, docs/topics/mta-rn-resolved-issues-6-2-2.adoc
* [MTA-2198](https://issues.redhat.com/browse/MTA-2198)
=> MTA-2198: release notes for MTA-6.2.2

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-7-0-2.adoc, docs/topics/mta-rn-known-issues-7-0-3.adoc, docs/topics/mta-rn-resolved-issues-7-0-3.adoc
* [MTA-2239](https://issues.redhat.com/browse/MTA-2239)
* [MTA 7-0-3](https://deploy-preview-874--windup-documentation.netlify.app/docs/release-notes/master/#mta-7-0-3)
* [Known issues](https://deploy-preview-874--windup-documentation.netlify.app/docs/release-notes/master/#rn-known-issues-7-0-3_release-notes)
* [Resolved issues](https://deploy-preview-874--windup-documentation.netlify.app/docs/release-notes/master/#mta-rn-resolved-issues-7-0-3_release-notes)
=> MTA-2239: Release Notes 7.0.3

docs/topics/templates/document-attributes.adoc
Jira tracker: https://issues.redhat.com/browse/MTA-2443.
=> Updated document attributes for the 7.0.3 release

docs/topics/templates/document-attributes.adoc
* [WINDUP-4173](https://issues.redhat.com/browse/WINDUP-4173)
=> WINDUP-4173: Doc Attributes updates for MTR-1.2.6

docs/release-notes/master.adoc, docs/topics/mta-rn-known-issues-6-2-3.adoc, docs/topics/mta-rn-resolved-issues-6-2-3.adoc
* [MTA-2603](https://issues.redhat.com/browse/MTA-2603)
=> MTA-2603: Release Notes for MTA-6.2.3

docs/topics/templates/document-attributes.adoc
* [MTA-2602](https://issues.redhat.com/browse/MTA-2602)
* No preview
```
:ProductVersion: 6.2.3
:PluginName: MTA plugin
:MavenProductVersion: 6.2.3.GA-redhat-00001
:ProductDistributionVersion: 6.2.3.GA-redhat
:ProductDistribution: mta-6.2.3.GA-cli-offline.zip
```
=> MTA-2602: Attributes Updates for MTA 6.2.3

docs/eclipse-code-ready-studio-guide/master.adoc, docs/topics/adding-jboss-tools-dependencies-for-the-mta-plug-in.adoc, docs/topics/eclipse-installing-plugin.adoc, docs/topics/installing-eclipse.adoc, docs/topics/installing-java-development-kit.adoc
The 7.0 version of https://github.com/migtools/mta-documentation/pull/52/files (7.1)
=> Adding new procedures to the Eclipse doc
