- docs/topics/cli-args.adoc
- docs/topics/create-basic-xml-rule.adoc
- docs/topics/create-first-xml-rule.adoc
- docs/topics/testing-rules.adoc
WINDUP-1721: Included the .rhamt.xml extension any place where rules extensions were referenced.
> WINDUP-1721: Including the .rhamt.xml extension.

- docs/cli-guide/master.adoc
- docs/topics/cli-args.adoc
- docs/topics/exclude-files-and-packages.adoc
- docs/topics/optimize-performance.adoc
I've updated the section in the CLI about optimizing performance, along with correcting a couple of minor issues found along the way.
@mrizzi,
Could you examine the changes and see if this appears good to you? In addition, please confirm the list of locations where files can be included, as `~/.rhamt/ignore/` was a guess based on the rule naming convention.
> WINDUP-2007: Included topic on excluding files and packages.

- docs/topics/templates/document-attributes.adoc
Corrected the Maven version to be `4.1.0.Final` in the document-attributes.adoc file. This now renders correctly.
> WINDUP-2107: Corrected maven version.

- docs/topics/cli-args.adoc
- docs/topics/maven-arguments.adoc
Updated the `enableTattletale` report in the CLI and Maven guides, and introduced the `disableTattletale` report option in the CLI and Maven guides.
> WINDUP-2180: Include the disableTattletale report option.

- docs/plugin-guide/master.adoc
- docs/topics/install-jboss-tools.adoc
- docs/topics/plugin-install.adoc
This includes the instructions for adding JBoss Tools into an Eclipse installation.
> WINDUP-2245: Included instructions for installing JBoss Tools.

- docs/topics/templates/document-attributes.adoc
Correcting the download link for the offline Eclipse Plugin install instructions.
> Corrected download link.

- docs/topics/maven-arguments.adoc
- docs/topics/maven-multi-module.adoc
- docs/topics/maven-run.adoc
Updated the details of the `windupVersion` argument and removed it from the examples.
@m-brophy, would you be able to review these changes?
> WINDUP-2269: Updated windupVersion description.

- docs/plugin-guide/master-docinfo.xml
- docs/plugin-guide/master.adoc
- docs/topics/about-plugin.adoc
- docs/topics/install-jboss-tools.adoc
- docs/topics/known_issues.adoc
- docs/topics/plugin-access-windup-tools.adoc
- docs/topics/plugin-identify-resolve-issues.adoc
- docs/topics/plugin-install.adoc
- docs/topics/plugin-supported-configs.adoc
- docs/topics/plugin-uninstall.adoc
- docs/topics/templates/document-attributes.adoc
This PR changes URL fragment from eclipse_plugin_guide to ide_plugin_guide
The title needs to be renamed in Pantheon to ensure builds work
> WINDUP-2484: 4.3.0 updates to the IDE Plugin Guide

- docs/topics_5/web-install-zip.adoc
resolves https://issues.redhat.com/browse/WINDUP-2706
by changing 100000 to 10000 in section 2.1 ("If you are running macOS, it is recommended to set the maximum number of user processes, maxproc, to at least 2048, and the maximum number of open files, maxfiles, to 100000.")
> 100 K -> 10 K

- docs/topics_5/rn-known-issues.adoc
- docs/topics_5/web-install-zip.adoc
MTA 5.0 does not support IE (added to known issues). Was tested against Chrome and Firefox (added to installation prerequisites).
> Browser support and IE known issue for MTA 5.0

- docs/topics_5/rn-known-issues.adoc
Adds https://issues.redhat.com/browse/WINDUP-2710 to top of known issues list for MTA version 5.0.0.
> Known issue (WINDUP-2710) added for MTA 5.0.0

- docs/topics_5/cli-prerequisites.adoc
- docs/topics_5/maven-prerequisites.adoc
- docs/topics_5/plugin-install.adoc
- docs/topics_5/rn-known-issues.adoc
- docs/topics_5/templates/document-attributes.adoc
- docs/topics_5/web-install-zip.adoc
1. Description of ulimit items in Known Issues changed to indicate that they were resolved in version 5.0.1 (as per Phil's request).
2. {ProductVersion} changed to 5.0.1 -- only impact on document is to change the name of file downloaded for installation of the Eclipse plugin. Change confirmed by Phil.
3. Resolved https://issues.redhat.com/browse/MIGENG-829 by removing the limits to ulimit that were in the documentation.
4. Other references to maxfiles removed.
> Changes for MTA 5.0.1

- docs/topics_5/web-execution-config.adoc
Only one occurrence in all version 5 files.
> Fix of product name: Open JDK -> OpenJDK

- docs/topics_5/installation.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2770.
Adds a note to the MTA web console installation instructions telling Windows users to choose "Yes" if they get a "Replace duplicate file" message during extraction of the .zip file.
> File duplication warning

- docs/topics_5/templates/document-attributes.adoc
- docs/topics_5/web-openshift-troubleshoot.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-2916
Preview: http://file.emea.redhat.com/rhoch/08122020/fixlinks/html-single/#troubleshoot_web_console_openshift_install_ocp-311
@apinnick: Please review.
> Broken links in MTA web console guide

- docs/topics_5/installing-web-console-on-openshift.adoc
Resolves https://issues.redhat.com/browse/WINDUP-2931
http://file.emea.redhat.com/rhoch/18012021/ocp_pre/html-single/#installing-web-console-on-openshift_ocp-45
> Prerequisites for installing MTA on OpenShift

- docs/getting-started-guide/master-docinfo.xml
- docs/getting-started-guide/master.adoc
- docs/topics/about-rules.adoc
- docs/topics/about-the-intro-to-mta-guide.adoc
- docs/topics/cli-args.adoc
- docs/topics/installing-web-console-on-openshift.adoc
- docs/topics/installing-web-console.adoc
- docs/topics/maven-arguments.adoc
- docs/topics/rules-guide-intro.adoc
- docs/topics/templates/document-attributes.adoc
- docs/topics/what-is-the-toolkit.adoc
Fixes the broken links in MTA docs issue raised in https://issues.redhat.com/browse/WINDUP-3014. 
Previews:
For the repaired link to _Introduction to the Migration Tools for Applications_ guide, formerly the _Getting Started Guide_:
http://file.emea.redhat.com/rhoch/01032021/clig/html-single/#about_mta_cli-guide
http://file.emea.redhat.com/rhoch/01032021/maveng/html-single/#about_mta_maven-guide
http://file.emea.redhat.com/rhoch/01032021/pluging/html-single/#about_mta_plugin-guide
http://file.emea.redhat.com/rhoch/01032021/rulesg/html-single/#about_rules_dev_guide_rules-development-guide
http://file.emea.redhat.com/rhoch/01032021/webcg/html-single/#about_mta_web-console-guide
For the repaired link to the IDE plugin download:
http://file.emea.redhat.com/rhoch/01032021/pluging/html-single/#i …
> Fixing broken links in MTA docs

- docs/topics/installing-web-console.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3049
Gives the user the correct link for the Eclipse .tar file to download.
> Only J2E version of eclipse tar works with MTA plugin

- docs/topics/installing-web-console.adoc
For MTA 5.1.3. 
Resolves: https://issues.redhat.com/browse/WINDUP-3049?focusedCommentId=16030031&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16030031
Corrects the file the user should download to use Eclipse with MTA 5.1.x 
Previews: Sections 2 and 3 (prerequisites): https://deploy-preview-415--windup-documentation.netlify.app/docs/plugin-guide/master/index.html#installing-web-console_plugin-guide
> Correct Eclipse download

- CONTRIBUTING.adoc
- README.md
- docs/topics/important-links.adoc
- docs/topics/proc_reporting-issues.adoc
- docs/topics/report-issues.adoc
- docs/topics/rules-important-links.adoc
- docs/topics/web-openshift-troubleshoot.adoc
Fixes broken links in MTA repo that point Jira boards for WINDUP and WINDUPRULES
(No Jira)
Previews: 
https://deploy-preview-420--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#troubleshooting-a-web-console-installation-on-openshift ("Reporting issues")  
Note -- it's possible a user reading this section might want to report an issue with OpenShift, not MTA, so I suggest leaving the title as is rather than change it to "Reporting issues with MTA" as in the two documents that follow.
https://deploy-preview-420--windup-documentation.netlify.app/docs/cli-guide/master/index.html#report_issues_cli-guide (A.4.3 "Reporting issues with MTA")
https://deploy-preview-420--windup-documentation.netlify.app/docs/maven-guide/master/index.html#report_issues_maven-guide (A.4.3 …
> Fix Jira links in MTA repo

- docs/topics/rn-new-features.adoc
MTA 5.1.4 (to be released 13 May 2021)
Resolves latest addition to https://issues.redhat.com/browse/WINDUP-3045.
Preview: "Rules for migrating from Thorntail to JBoss EAP XP 2" in https://deploy-preview-424--windup-documentation.netlify.app/docs/release-notes/release_notes-5.1/master/index.html#rn-new-features_release-notes
> MTA 5.1.4 release notes: Thorntail -> JBoss EAP XP 2

- docs/cli-guide/master.adoc
- docs/maven-guide/master.adoc
- docs/rules-development-guide/master.adoc
- docs/topics/about-story-points.adoc
- docs/topics/overriding-rules.adoc
- docs/topics/rule-categories.adoc
MTA 5.1.3 (current release)
Fixed a bad xref and corrected two minor typos.
> Fixed xref to Rules Development Guide

- docs/maven-guide/master.adoc
- docs/topics/installing-plugin.adoc
- docs/topics/maven-run.adoc
- docs/topics/templates/document-attributes.adoc
MTA version 5.1.4
Resolves: https://issues.redhat.com/browse/WINDUP-3097 -- removes redundant section and changes the Maven product version in the parent project’s pom.xml file.
Preview: https://deploy-preview-427--windup-documentation.netlify.app/docs/maven-guide/master/index.html#getting-started
Note: in making this change, I needed to modify the installation file used for IDE Plugin Guide. I verified that the guide builds properly and that its content was unchanged by the changes made here.
> MTA Maven Plugin Guide: corrected installation procedures

- docs/topics/installing-web-console-on-openshift.adoc
- docs/web-console-guide/master.adoc
MTA 1.5.4
Resolves: https://issues.redhat.com/browse/WINDUP-3113.  OCP 3.11 will no longer be supported from 1st July.
Note that there are no other references to OCP 3.11 in the rest of the MTA repo. 
Preview of installation chapter: https://deploy-preview-437--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#installing-the-web-console
I have checked this "manually" to ensure that all remaining installation prerequisites and procedures were not affected.
> Remove all references to installing MTA on OCP 3.11

- docs/topics/eclipse-installing-plugin.adoc
MTA 5.2
Resolves: https://issues.redhat.com/browse/WINDUP-3135
Preview: https://deploy-preview-449--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide/master/index.html#installing-plugin_eclipse-code-ready-studio-guide
> MTA 5.2: Update Eclipse and CRS versions

- docs/vs-code-extension-guide/master.adoc
MTA 5.2
Applies headline style to the title of the VS Code extension guide
> Headline style applied to title of VS Code extension guide

- docs/topics/about-vscode-extension.adoc
- docs/topics/eclipse-installing-plugin.adoc
- docs/topics/eclipse-reviewing-issues.adoc
- docs/topics/installing-vs-code-extension.adoc
- docs/topics/installing-web-console-or-cli-tool.adoc
- docs/topics/maven-run.adoc
- docs/topics/plugin-icon-legend.adoc
- docs/topics/system-requirements.adoc
- docs/topics/vs-code-extension-reviewing-issues.adoc
- docs/topics/what-is-the-toolkit.adoc
Resolves second set of requests in https://issues.redhat.com/browse/WINDUP-3167
Previews:
1. "Technology preview" note removed from description of VS Code extension: https://deploy-preview-456--windup-documentation.netlify.app/docs/vs-code-extension-guide/master/index.html#about-vscode-extension_vsc-extension-guide
2. Changes to bulleted list in "What is the Migration Toolkit  for Applications": https://deploy-preview-456--windup-documentation.netlify.app/docs/vs-code-extension-guide/master/index.html#what-is-the-toolkit_vsc-extension-guide
3. Prerequisites for Eclipse/CodeReady Studio plugin (same for both connected and disconnected environments): https://deploy-preview-456--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide/master/index.html#eclipse-installing-plugin-c …
> Small changes to Eclipse/CodeReady Studio and VS Code guides

- docs/topics/templates/document-attributes.adoc
MTA 5.2.1
Partially resolves: https://issues.redhat.com/browse/WINDUP-3196 (MTA 5.2.1. documentation changes0
Updates OCP and MTA component version numbers for MTA 5.2.1.
Preview: NA.
> Version number updates for MTA 5.2.1

- docs/topics/rn-known-issues.adoc
MTA 5.2.1
Partially resolves https://issues.redhat.com/browse/WINDUP-3196 (known issues).
Preview: https://deploy-preview-466--windup-documentation.netlify.app/docs/release-notes/master/index.html#rn-known-issues_release-notes
Note that version number will be corrected in this and all PRs in a separate PR that adjusts all version numbers in the document set.
> MTA 5.2.1 release notes: known issues

- docs/cli-guide/master-docinfo.xml
- docs/cli-guide/master.adoc
- docs/eclipse-code-ready-studio-guide/master-docinfo.xml
- docs/eclipse-code-ready-studio-guide/master.adoc
- docs/getting-started-guide/master-docinfo.xml
- docs/getting-started-guide/master.adoc
- docs/maven-guide/master-docinfo.xml
- docs/maven-guide/master.adoc
- docs/release-notes/master-docinfo.xml
- docs/release-notes/master.adoc
- docs/rules-development-guide/master-docinfo.xml
- docs/rules-development-guide/master.adoc
- docs/topics/templates/document-attributes.adoc
- docs/web-console-guide/master-docinfo.xml
- docs/web-console-guide/master.adoc
MTA 5.2.x
No Jira.
Replaces document title attributes with actual titles throughout the MTA repo in master.adoc and master-docinfo.xml files. Removes attributes that are used only in these files.
> Draft: Replacing attributes with actual titles

- docs/eclipse-code-ready-studio-guide/master-docinfo.xml
- docs/topics/about-the-intro-to-mta-guide.adoc
- docs/topics/create-first-xml-rule.adoc
- docs/topics/eclipse-installing-plugin.adoc
- docs/topics/maven-access-reports.adoc
- docs/topics/maven-multi-module.adoc
- docs/topics/maven-run.adoc
- docs/topics/method-deploy.adoc
- docs/topics/optimize-performance.adoc
- docs/topics/overriding-rules.adoc
- docs/topics/plugin-components.adoc
- docs/topics/review-reports.adoc
- docs/topics/rn-known-issues.adoc
- docs/topics/rn-new-features.adoc
- docs/topics/rn-resolved-issues.adoc
- docs/topics/validation-report.adoc
- website/docs/topics/proc_cli-execute.adoc
MTA 5.2.1 Resolves later requirements of https://issues.redhat.com/browse/WINDUP-3196
Previews:
1. Release notes (complete): http://file.emea.redhat.com/rhoch/06122021/release_notes/html-single/
2. Eclipse guide -- prerequisites for both connected and disconnected environments: http://file.emea.redhat.com/rhoch/06122021/eclipse/html-single/#eclipse-installing-plugin-connected-environment_eclipse-code-ready-studio-guide
> Revised MTA 5.2.1. Release notes and modified Eclipse/CodeReady Studio instructions

- docs/topics/eclipse-configuring-run.adoc
MTA 5.2.1
An image in the Eclipse guide did not appear because an incorrect file name appeared in the document.  
This PR resolves that problem.
> MTA Eclipse guide: fixed missing icon problem

- docs/intellij-idea-plugin-guide/master.adoc
- docs/topics/installing-intellij-idea-plugin.adoc
MTA 5.2.1
Partially resolves https://issues.redhat.com/browse/WINDUP-3207
This PR contains the text of the installation chapter of the IntelliJ IDEA plugin guide.
Preview of installation chapter: https://deploy-preview-505--windup-documentation.netlify.app/docs/intellij-idea-plugin-guide/master/index.html#intellij-idea-plugin-extension_idea-plugin
John, just so you know, this PR includes a change to the way the repo calls the prerequisites for installing the IDEs and other add-ons. You can ignore changes to every file in this PR except installing-intellij-plugin.adoc.
> IntelliJ IDEA guide: installation chapter

- docs/topics/installing-web-console-on-openshift.adoc
- docs/web-console-guide/master.adoc
MTA 5.2.1+
The procedure for installing the MTA web console on OCP varies with the OCP version. Originally, there was one set of instructions for OCP 4.1-4.4 and another for 4.5+. To make full use of modularization, two context variables were introduced in the  document's files, `ocp-41` and `ocp-45`. As the product matures, the first set of instructions was applied to OCP version 4.2-4.5 and the second to version 4.6+. The text of the document was changed but the context variables were not. Since the variables are simply names, they had no impact on the document, but unless one knows the history of the document, it is not clear why `ocp-41` refers to OCP versions 4.2-4.5 and `ocp-45` refers to OCP version 4.6+. This PR changes the names of the variables to `ocp-42` and `ocp-46` …
> Aligning context names with OCP version numbers

- docs/intellij-idea-plugin-guide/master.adoc
- docs/topics/intellij-idea-plugin-run-configuration.adoc
MTA 5.2.1
Partially resolves https://issues.redhat.com/browse/WINDUP-3207
This PR contains the text of the usage (run configuration) chapter of the IntelliJ IDEA plugin guide. the title is parallel with other IDE guides. 
Preview of chapter: https://deploy-preview-516--windup-documentation.netlify.app/docs/intellij-idea-plugin-guide/master/index.html#analyzing-projects-with-idea-plugin
> IntelliJ IDEA guide: usage

- docs/intellij-idea-plugin-guide/master.adoc
- docs/topics/installing-intellij-idea-plugin.adoc
Changed "extension" to "plugin" where needed in IntelliJ user guide
> Change extension to plugin in IntelliJ

- docs/topics/rn-known-issues.adoc
MTA 5.3.0 release notes
Resolves https://issues.redhat.com/browse/WINDUP-3368 by adding another item to the table of prominent known issues. 
Preview: https://deploy-preview-538--windup-documentation.netlify.app/docs/release-notes/master/index.html#rn-known-issues_release-notes [Last item in table]
> Additional item for MTA 5.3.0 known issues

- docs/topics/templates/document-attributes.adoc
Adds new attribute, LC_PSN, lower case product short name to repo to make it possible to consistently write "mta" or "mtr" in documents.
> New attribute:LC_PSN (lower case product short name)

- docs/topics/mta-web-proxy-config.adoc
- docs/web-console-guide/master.adoc
MTA 6.0
Resolves: https://issues.redhat.com/browse/TACKLE-802
Preview: https://deploy-preview-562--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#configuring-http-and-https-proxy-settings
> Tackle-802: Proxy configuration for MTA 6.0

- docs/topics/about-the-mta-operator.adoc
- docs/topics/about-the-user-interface.adoc
- docs/topics/mta-6-installing-web-console-on-openshift.adoc
- docs/topics/mta-about-console-guide.adoc
- docs/topics/mta-about-the-intro-to-mta-guide.adoc
- docs/topics/mta-web-application-attributes.adoc
- docs/topics/mta-web-assessing-apps.adoc
- docs/topics/mta-web-reviewing-an-analysis-report.adoc
- docs/topics/mta-what-is-the-toolkit.adoc
- docs/web-console-guide/master.adoc
Preview of installation instructions: https://deploy-preview-616--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#installing-the-migration-toolkit-for-applications-operator-and-the-user-interface
Preview of entire UI guide: https://deploy-preview-616--windup-documentation.netlify.app/docs/web-console-guide/master/index.html  [The phrase "Web Console Guide" at the top of the preview appears only in the Deploy Preview.]
> Rebuilds MTA User interface guide; fixes installation instructions

- docs/topics/create-first-xml-rule.adoc
- docs/topics/maven-access-reports.adoc
- docs/topics/mta-web-reviewing-an-analysis-report.adoc
- docs/topics/rules-guide-intro.adoc
- docs/topics/web-review-reports.adoc
MTA 6.0/MTR 1.0
Resolves https://issues.redhat.com/browse/TACKLE-875 by fixing links to the "Reviewing the reports" section of the CLI guide (Previews 1-3) and fiixes incorrect link in the Rules Development Guide (preview 4) .  
Previews:
1. See "Reviewing the rules" in https://deploy-preview-622--windup-documentation.netlify.app/docs/rules-development-guide/master/index.html#create-first-xml-rule_rules-development-guide  [MTA] and https://deploy-preview-622--windup-documentation.netlify.app/docs/rules-development-guide-mtr/master/index.html#create-first-xml-rule_rules-development-guide-mtr [MTR]
2. See "Reviewing an analysis report"  in https://deploy-preview-622--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-reviewing-an-analysis-report_user-interface- …
> TACKLE-875: Correct link for 'Reviewing the reports"

- docs/topics/create-first-xml-rule.adoc
- docs/topics/review-existing-rules.adoc
- docs/topics/rules-testing-junit.adoc
MTA 6.0/MTR 1.0
Resolves https://issues.redhat.com/browse/TACKLE-876 with a number of small fixes:
Jira items 1, 2, and 3 resolved in Jira.
Item 4: First link in https://deploy-preview-625--windup-documentation.netlify.app/docs/rules-development-guide/master/index.html#review-existing-rules_rules-development-guide
Item 5: Last paragraph of https://deploy-preview-625--windup-documentation.netlify.app/docs/rules-development-guide/master/index.html#rules-testng-junit_rules-development-guide
Item 6: Last paragraph of https://deploy-preview-625--windup-documentation.netlify.app/docs/rules-development-guide/master/index.html#create-first-xml-rule_rules-development-guide
Item 7: Space beteween figures and titles in https://deploy-preview-625--windup-documentation.netlify.app/docs/rules-developmen …
> TACKLE-876: Fix links and other errors in the Rules Development guide

- docs/web-console-guide/master.adoc
MTA 6.0
Resolves https://issues.redhat.com/browse/TACKLE-880 
Previews: 
1. https://deploy-preview-626--windup-documentation.netlify.app/docs/web-console-guide/master/index.html (You can see that chapters 7 and 8 are gone).
2. https://deploy-preview-626--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-6-ui-interface-views ["u" removed from "uviews."]
3. https://deploy-preview-626--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#configuring-maven-repositories ["(ProductShortName)" no longer appears.]
> Removes MTR sections from MTA UI guide

- docs/eclipse-code-ready-studio-guide/master.adoc
- docs/vs-code-extension-guide/master.adoc
MTA 6.0
Resolves https://issues.redhat.com/browse/TACKLE-878 by fixing a link in the "About the Migration Toolkit for Applications" section of the Eclipse guide (same problem fixed throughout repo).
Preview: https://deploy-preview-627--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide/master/index.html#mta-what-is-the-toolkit_eclipse-code-ready-studio-guide
> Fixes link in "About the Migration Toolkit for Appplications" section

- docs/topics/eclipse-configuring-run.adoc
MTA 6.0 Eclipse guide -- bad link to "About MTA command-line arguments"
> Fixes bad link in Eclipse guide

- docs/topics/cli-run.adoc
MTA 6.0/MTR 1.0
Adds space between code blocks and discrete headings in the CLI guide.
> Spacing between code blocks and discrete headings 

- docs/topics/cli-run.adoc
MTA 6.0
Increases spacing between code blocks and discrete headings in section 2.2 of the  CLI guide
> Spacing again

- docs/topics/maven-multi-module.adoc
- docs/topics/maven-run.adoc
- docs/topics/templates/document-attributes.adoc
MTR 1.0.1
Resolves https://issues.redhat.com/browse/WINDUP-3622 by updating the product version number in MTR documentation set to 1.0.1 where needed.
Previews:
1. https://deploy-preview-648--windup-documentation.netlify.app/docs/cli-guide-mtr/master/index.html#tech-tags_cli-guide  Correct version number: 1.0.1
2. https://deploy-preview-648--windup-documentation.netlify.app/docs/intellij-idea-plugin-guide-mtr/master/index.html#intellij-idea-plugin-run-configuration_idea-plugin-guide step 4: cli example -- For example: $HOME/mtr-cli-1.0.1.GA-redhat-00003/bin/windup-cli
3. https://deploy-preview-648--windup-documentation.netlify.app/docs/vs-code-extension-guide-mtr/master/index.html#vs-code-extension-run-configuration_vsc-extension-guide-mtr step 3: cli example -- For example: …
> z-stream version numbers in repo

- docs/topics/mta-6-installing-web-console-on-openshift.adoc
MTA 6.0
Resolves: https://issues.redhat.com/browse/TACKLE-914 by adding CR settings to the user interface installation procedure.
Preview: https://deploy-preview-639--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-6-installing-web-console-on-openshift_user-interface-guide
Changed: 
In section 3.2, steps 7-10 have been changed and Table 2 has been added.
> TACKLE-914: Add CR settings to UI installation procedure

- docs/release-notes/master-docinfo.xml
- docs/release-notes/master.adoc
- docs/topics/mta-6-installing-web-console-on-openshift.adoc
- docs/topics/mta-rn-known-issues-1.adoc
- docs/topics/mta-rn-new-features-1.adoc
- docs/topics/mta-rn-new-features.adoc
- docs/topics/mta-rn-resolved-issues-1.adoc
- docs/topics/mta-rn-upgrade-cli.adoc
- docs/topics/mta-rn-upgrade-ui.adoc
- docs/topics/templates/document-attributes.adoc
MTA 6.0.1
Resolves https://issues.redhat.com/browse/MTA-94 and https://issues.redhat.com/browse/MTA-148 by creating release notes for MTA 6.0.1, including the new RWX option.
Also adds a sample YAML to the User interface user guide installation instructions.
Previews: 
1. The MTA 6.0.1 release notes: https://deploy-preview-653--windup-documentation.netlify.app/docs/release-notes/master/index.html#mta-6-0-1
2. The added YAML file: https://deploy-preview-653--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#installing-the-migration-toolkit-for-applications-operator-and-the-user-interface  follows table of CR settings
> Release notes for MTA 6.0.1 including RWX parameter

- docs/topics/mta-6-installing-web-console-on-openshift.adoc
- docs/topics/mta-rn-new-features-1.adoc
- docs/topics/mta-rn-upgrade-cli.adoc
- docs/topics/mta-rn-upgrade-ui.adoc
MTA 6.0.1
Resolves https://issues.redhat.com/browse/MTA-148 by changing the description of the RWX permissions feature and fixing the headings of sections 2.1.1 and 2.1.2.
Also changes "repository" to "cache" in installation instructions where needed.
Previews: 
1. https://deploy-preview-659--windup-documentation.netlify.app/docs/release-notes/master/index.html#mta-6-0-1 Revised release notes for MTA 6.0.1
2a. https://deploy-preview-659--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#persistent-volume-requirements  description of "cache" PV.
2b. https://deploy-preview-659--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#installing-the-migration-toolkit-for-applications-operator-and-the-user-interface  Table 2 -- description of …
> Revised MTA 6.0.1 release notes

- docs/eclipse-code-ready-studio-guide-mtr/master.adoc
- docs/topics/eclipse-configuring-plugin-for-cli.adoc
- docs/topics/eclipse-installing-plugin.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3757
MTR 1.1.0
Preview: https://deploy-preview-670--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide-mtr/master/index.html#installing-plugin_eclipse-code-ready-studio-guide
> WINDUP-3757: Update Eclipse/CRS Guide for CLI configuration

- docs/topics/templates/document-attributes.adoc
[MTV-145](https://issues.redhat.com/browse/MTA-145)
Changing the document-attributes.adoc file for moving from 6.0.1 release to 6.1.0 release
> MTA-145: changing the references to earlier versions

- docs/topics/about-the-user-interface.adoc
- docs/topics/mta-web-config-git-repos.adoc
- docs/topics/mta-web-config-http-https-proxy.adoc
- docs/topics/mta-web-config-subversion-repos.adoc
- docs/topics/mta-what-is-the-toolkit.adoc
- docs/topics/new-mta-features.adoc
- docs/topics/xml-rule-syntax.adoc
[MTA-519](https://issues.redhat.com/browse/MTA-519)
Fixing a number of typos:
/windup-documentation/topics/mta-what-is-the-toolkit.adoc:
**questionaire as the the** changed to **questionnaire as the**
"Migrating EAP Java applicatons to Azure App Service"
/windup-documentation/topics/new-mta-features.adoc:
**Enhanced Role-Bassed Access Control** changed to  **Enhanced Role-Based Access Control**
/windup-documentation/topics/about-the-user-interface.adoc:
**users to assess and analayze applications** changed to **users to assess and analayze applications**
/windup-documentation/topics/mta-web-config-git-repos.adoc:
/windup-documentation/topics/mta-web-config-http-https-proxy.adoc:
/windup-documentation/topics/mta-web-config-subversion-repos.adoc:
**respositories** changed to …
> MTA-519 - Fixing a number of typos

- docs/topics/mta-rn-known-issues-6-1-0.adoc
- docs/topics/mta-rn-known-issues-6-1-1.adoc
- docs/topics/mta-rn-resolved-issues-6-1-0.adoc
- docs/topics/mta-rn-resolved-issues-6-1-1.adoc
Adding fixes to address:
[31m[1mID "rn-known-issues-1_release-notes" is duplicated in the source content[0m
[31m[1mID "mta-rn-resolved-issues-1_release-notes" is duplicated in the source content[0m
[31m[1m/var/lib/jenkins/workspace/doc-migration_toolkit_for_applications-6.1-release_notes-en-US (stage)/docs/release-notes/build/en-US/master.xml fails to validate[0m
Build step 'Execute shell' marked build as failure
> add changes to fix error of rn-known-issues-1_release-notes

- docs/topics/templates/document-attributes.adoc
Updating the attributes doc to update references to 6.1.1
Please can I ask for verification of the names of the new packages.
Lines 26 to 28:
:MavenProductVersion: 6.1.1.GA-redhat-00005
:ProductDistributionVersion: 6.1.1.GA-redhat
:ProductDistribution: mta-6.1.1.GA-offline.zip
Thanks
> MTA-524: updating attributes for MTA-6.1.1 GA

- docs/topics/templates/document-attributes.adoc
[WINDUP-3694](https://issues.redhat.com/browse/WINDUP-3694): MTR1.1.0-attributes update.
changes made to `document-attributes.adoc` lines 35 to 54
```
ifdef::mtr[]
> :ProductName: Migration Toolkit for Runtimes
> :DocInfoProductName: Migration Toolkit for Runtimes
> :DocInfoProductNumber: 1.1
> :ProductShortName: MTR
> :LC_PSN: mtr
> :DocInfoProductNameURL: migration_toolkit_for_runtimes
> :WebName: web console
> :WebNameTitle: Web Console
> :WebNameURL: web_console_guide
> :WebConsoleBookName: {WebNameTitle} Guide
> :ProductVersion: 1.1.0
> :PluginName: MTR plugin
> :ProductDistributionVersion: 1.1.0.GA-redhat-00003
> :ProductDistribution: mtr-1.1.0.GA-offline
> :DevDownloadPageURL: https://developers.redhat.com/products/mtr/download
> :IDEPluginFilename: …
```
> WINDUP-3694: MTR1.1.0-attributes update

- docs/topics/mtr-rn-known-issues-1_1_0.adoc
- docs/topics/mtr-rn-new-features-1_1_0.adoc
- docs/topics/mtr-rn-resolved-issues-1_1_0.adoc
Fixing broken IDs in MTR 1.1.0 release notes
> Fixing error in MTR 1.1.0 release notes: duplicate IDs

- docs/topics/eclipse-installing-plugin.adoc
- docs/topics/snippet_jdk-hardware-mac-prerequisites.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3603
MTR 1.1.0
Preview: 
https://deploy-preview-687--windup-documentation.netlify.app/docs/cli-guide-mtr/master/index.html#installing-web-console-or-cli-tool_cli-guide
https://deploy-preview-687--windup-documentation.netlify.app/docs/web-console-guide-mtr/master/index.html#installing-web-console-linux-win-mac_web-console-guide
https://deploy-preview-687--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide-mtr/master/index.html#eclipse-installing-plugin_eclipse-code-ready-studio-guide
https://deploy-preview-687--windup-documentation.netlify.app/docs/intellij-idea-plugin-guide-mtr/master/index.html#intellij-idea-plugin-extension_idea-plugin-guide
https://deploy-preview-687--windup-documentation.netlify.app/docs/vs-code-exten …
> WINDUP-3603 Run Windup on OpenJDK17 - Changes to Docs

- docs/topics/maven-run.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3785
MTR 1.0 and later
MTA 6.0.0 and later
Preview: https://deploy-preview-693--windup-documentation.netlify.app/docs/maven-guide-mtr/master/index.html#maven-run_maven-guide
> WINDUP-3785 MTA and MTR Maven Plugins - direct Maven to use the JBoss EAP Maven Respository

- docs/topics/eclipse-installing-plugin.adoc
Resolves: https://issues.redhat.com/browse/WINDUP-3759
MTR 1.1.0
Preview:
https://deploy-preview-690--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide-mtr/master/index.html#eclipse-installing-plugin_eclipse-code-ready-studio-guide
https://deploy-preview-690--windup-documentation.netlify.app/docs/eclipse-code-ready-studio-guide/master/index.html#eclipse-installing-plugin_eclipse-code-ready-studio-guide
> WINDUP-3759 Update Eclipse/CRS Guide to get plugin from Eclipse Marketplace

- docs/release-notes-mtr/master.adoc
- docs/topics/mtr-rn-cgo-1_1_1.adoc
- docs/topics/mtr-rn-resolved-issues-1_1_1.adoc
[WINDUP-3946](https://issues.redhat.com/browse/WINDUP-3946)
Release Notes for MTR 1.1.1
Adding release notes to cover CGO only release
Direct preview - https://deploy-preview-709--windup-documentation.netlify.app/docs/release-notes-mtr/master/index.html#mtr-rn-resolved-issues-111_release-notes
> WINDUP-3946: release notes for MTR 1.1.1 cgo release

- docs/topics/create-first-xml-rule.adoc
- docs/topics/review-quickstarts.adoc
- docs/topics/rule-categories.adoc
**NOT URGENT**
@RichardHoch - will tidy up later and include links so you see the docs, but please let me get there 
Thanks
* https://deploy-preview-734--windup-documentation.netlify.app/docs/rules-development-guide/master/#creating-directory-structure-for-the-rule_rules-development-guide
* https://deploy-preview-734--windup-documentation.netlify.app/docs/rules-development-guide/master/#review-quickstarts_rules-development-guide
* https://deploy-preview-734--windup-documentation.netlify.app/docs/rules-development-guide/master/#rule-categories_rules-development-guide
Chapters 2 and 6 have some unnumbered headings that I think should be numbered. Probably not worth holding up publication but might be worth a Jira down the road.
* Section 2.1: …
> Updating level 2 headers and adding IDs

- docs/release-notes-mtr/master.adoc
- docs/topics/mta-rn-new-features-6-2-0.adoc
- docs/topics/mtr-rn-known-issues-1-2-0.adoc
- docs/topics/mtr-rn-new-features-1-2-0.adoc
- docs/topics/mtr-rn-resolved-issues-1-2-0.adoc
[Windup-3997](https://issues.redhat.com/browse/WINDUP-3997)
[PREVIEW](https://deploy-preview-746--windup-documentation.netlify.app/docs/release-notes-mtr/master/)
I have reverted the erroneous commit in Hagay's PR (see [Hagay's PR)](https://github.com/windup/windup-documentation/pull/736).
I think Phil likes to include earlier releases in his JIRA filter for known issue. It is consistent with filters he has provided previously.
> Windup 3997 mtr 1 2 0 release notes hvider 

- docs/eclipse-code-ready-studio-guide-mtr/master-docinfo.xml
- docs/eclipse-code-ready-studio-guide-mtr/master.adoc
- docs/eclipse-code-ready-studio-guide/master-docinfo.xml
- docs/eclipse-code-ready-studio-guide/master.adoc
- docs/topics/about-tools.adoc
- docs/topics/eclipse-about-plugin.adoc
- docs/topics/eclipse-accessing-tools.adoc
- docs/topics/eclipse-configuring-run.adoc
- docs/topics/eclipse-installing-plugin.adoc
- docs/topics/getting-started-about-ide-addons.adoc
- docs/topics/method-deploy.adoc
- docs/topics/plugin-intro.adoc
- docs/topics/rules-testing-junit.adoc
- docs/topics/templates/document-attributes.adoc
- index.md
- website/index.md
Removed mentions of "Red Hat CodeReady Studio" from MTR documentation
Referred issue: WINDUP-4036  https://issues.redhat.com/browse/WINDUP-4036
> Removed mention of Red Hat CodeReady Studio

- docs/topics/templates/document-attributes.adoc
@RichardHoch && @sbeskin-redhat - please review
Updating URL so as consistent with Pantheon:
Please check, approve and merge
Thanks
> Fixing Eclipse URL in document-attributes.adoc

- docs/cli-guide/master.adoc
- docs/topics/mta-cli-analyze.adoc
- docs/topics/mta-cli-transform.adoc
- docs/topics/templates/document-attributes.adoc
https://issues.redhat.com/browse/MTA-1289
- Adding 2 new modules to the CLI Guide: 
- Analyze command:  _cli-guide/topics/mta-cli-analyze.adoc_
- Transform command:   _cli-guide/topics/mta-cli-transform.adoc_
- Created new attribute for the CLI command name, added it to the templates/document-attributes.adoc file: 
mta-cli
> MTA-1289 adding new mta cli commands: Analyze and Transform

- docs/getting-started-guide/master.adoc
- docs/maven-guide/master.adoc
- index.md
* [MTA-2066](https://issues.redhat.com/browse/MTA-2066)
* [Preview section showing Maven Plugin Guide removed](https://deploy-preview-812--windup-documentation.netlify.app/)
> MTA 2066: remove Maven docs as Maven plugin deprecated

- docs/release-notes/master.adoc
- docs/topics/mta-rn-known-issues-7-0-0.adoc
- docs/topics/mta-rn-known-issues.adoc
- docs/topics/mta-rn-new-features-7-0-0.adoc
- docs/topics/mta-rn-resolved-issues-7-0-0.adoc
- docs/topics/mta-rn-technical-changes-7-0-0.adoc
- docs/topics/mta-rn-upgrade-notes-7-0-0.adoc
- docs/topics/technology-preview.adoc
* [MTA-1180](https://issues.redhat.com/browse/MTA-1180)
* [MTA 7.0.0 release notes](https://deploy-preview-804--windup-documentation.netlify.app/docs/release-notes/master/#rn-new-features-7-0-0_release-notes)
* There are two languages at this time . Java and Go out of which Go is Tech Preview only.
* The new feature list is missing :
1. Enhanced assessment module with custom questionnaire
2. Grouping applications for assessment into archetypes.
3. Unlink applications from JIRA
*
> MTA-1180: Release notes for v7.0.0

- docs/topics/configuring-web-console-authentication-for-linux-windows-macos.adoc
- docs/topics/installing-web-console-on-openshift.adoc
- docs/topics/vs-code-extension-run-configuration.adoc
https://issues.redhat.com/browse/MTA-2103
Replace "windup" and "windup-cli" references with attributes  {LC_PSN} and {mta-cli}
https://docs.google.com/document/d/1W9FjPuCHQlStZXqiDCTZq66Bq_5EDoqrS2cQEqyJrB4/edit
Potential targets for update:
DONE /configuring-web-console-authentication-for-linux-windows-macos.adoc realm named windup , windup-web , SSO_REALM=windup , SSO_CLIENT_ID=windup-web
UNCHANGED (already contains some attributes) 
/exclude-files-and-packages.adoc .windup-ignore.txt
UNCHANGED - GITHUB addresses  /fork-ruleset-repo.adoc windup-rulesets repository
REVERTED CHANGES - belongs to MTR docs!  /installing-web-console-on-openshift.adoc realm named windup , client named windup-web
DONE in a separate PR   /mta-cli-transform.adoc windup-shim_
NOT FOUND    /plugin-install.adoc …
> MTA-2103  insert attributes instead of "windup" and "windup-cli"

- docs/topics/vs-code-extension-interface.adoc
* [MTA-2161](https://issues.redhat.com/browse/MTA-2161)
* [3.1. MTA extension interface](https://deploy-preview-838--windup-documentation.netlify.app/docs/vs-code-extension-guide/master/#vs-code-extension-interface_vsc-extension-guide)
I have removed the screenshot, if I get time in the next few weeks, I come back and replace it.
> MTA-2161: VS Code screenshot is outdated

- docs/topics/mta-rn-known-issues-7-0-0.adoc
* [MTA-2288](https://issues.redhat.com/browse/MTA-2288)
* Added as Known issue to MTA 7.0.0
* Collapsible blocks added `To view the javax-package-custom-target.windup.xml, click (here).` and `To view the 01-javax-package-custom-target.windup.yaml, click (here).`
* [Known issues-7-0-0_release-notes](https://deploy-preview-865--windup-documentation.netlify.app/docs/release-notes/master/#rn-known-issues-7-0-0_release-notes)
> MTA-2288: Adding Custom Rule for Javax package to Known Issues

- docs/topics/mta-7-installing-web-console-on-openshift.adoc
Update MTA [Installation instructions](https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/7.0/html-single/user_interface_guide/index#mta-7-installing-web-console-on-openshift_user-interface-guide) to include all OpenShift editions, both [cloud](https://www.redhat.com/en/technologies/cloud-computing/openshift#cloud-services-editions) and [self managed](https://www.redhat.com/en/technologies/cloud-computing/openshift#self-managed).
> [MTA-2660] Updating installation instructions

- docs/topics/create-first-yaml-rule.adoc
- docs/topics/create-yaml-rule.adoc
- docs/topics/review-existing-rules.adoc
- docs/topics/rules-important-links.adoc
- docs/topics/templates/document-attributes.adoc
- docs/topics/testing-rules.adoc
- docs/topics/yaml-rule-structure-syntax.adoc
MTA 7.0
Resolves https://issues.redhat.com/browse/MTA-2919 by repairing 3 broken links in the Rules development guide and commenting out 1 that is irrelevant.
Also makes a number of small corrections to the guide:
Previews:
Broken links repaired:
https://file.emea.redhat.com/rhoch/broken_links_rules_dev/html-single/#test_xml_rule_syntax [Links in section for "InterableFilter," "ClassificationExists," and "HintsExist."]
Broken link commented out because the Java docs link on the windup website is broken:
https://file.emea.redhat.com/rhoch/broken_links_rules_dev/html-single/#rules-important-links_rules-development-guide [Link to "Javadocs" in Appendix 2.2 removed (commented out in rules-important-links.adoc)]
Small changes to other files:
- …
> Fix broken links in Rules development guide (MTA 7.0) 
